DROP TABLE IF EXISTS REPORTS;
DROP TABLE IF EXISTS ASSIGNED_TO;
DROP TABLE IF EXISTS BUG_STATUS;
DROP TABLE IF EXISTS CC_CLEAN;
DROP TABLE IF EXISTS COMPONENT;
DROP TABLE IF EXISTS OP_SYS;
DROP TABLE IF EXISTS PRIORITY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS RESOLUTION;
DROP TABLE IF EXISTS SEVERITY;
DROP TABLE IF EXISTS VERSION;



CREATE TABLE REPORTS (
ID			INTEGER
, CURRENT_RESOLUTION	TEXT
, CURRENT_STATUS	TEXT
, OPENING		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID)
);

CREATE TABLE ASSIGNED_TO (
ID			INTEGER
, CURRENT_EMPLOYEE	TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);


CREATE TABLE CC_CLEAN (
ID			INTEGER
, WHO     		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME, REPORTER)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE COMPONENT (
ID			INTEGER
, SUBSYSTEM		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE OP_SYS (
ID			INTEGER
, OP_SYS		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE PRIORITY (
ID			INTEGER
, PRIORITY		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE PRODUCT (
ID			INTEGER
, PRODUCT		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE RESOLUTION (
ID			INTEGER
, RESOLUTION		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE SEVERITY (
ID			INTEGER
, SEVERITY		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE VERSION (
ID			INTEGER
, VERSION		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, UPDATE_TIME)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);

CREATE TABLE BUG_STATUS (
ID			INTEGER
, STATUS		TEXT
, UPDATE_TIME		INTEGER
, REPORTER		INTEGER
, PRIMARY KEY (ID, STATUS, UPDATE_TIME, REPORTER)
, FOREIGN KEY (ID) REFERENCES REPORTS (ID)
);



.separator ,
.import reportsnew.csv REPORTS
;

.separator ,
.import assignedtonew.csv ASSIGNED_TO
;


.separator ,
.import ccnew.csv CC_CLEAN
;

.separator ,
.import componentnew.csv COMPONENT
;

.separator ,
.import opsysnew.csv OP_SYS
;

.separator ,
.import priority.csv PRIORITY
;

.separator ,
.import product.csv PRODUCT
;

.separator ,
.import resolutionnew.csv RESOLUTION
;

.separator ,
.import severity.csv SEVERITY
;

.separator ,
.import versionnew.csv VERSION
;

.separator ,
.import bug_status.csv BUG_STATUS
;

.headers on
.mode column
.output stdout;
